version: '3'
services:
  identity-data-processor:
    image: identity-data-processor:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - api.env
    network_mode: "host"
